"""Report Viewer page for generated stakeholder reports."""

from __future__ import annotations

from datetime import datetime
from html import escape
from pathlib import Path
import threading
from typing import List, cast

import streamlit as st
from streamlit.runtime.scriptrunner import add_script_run_ctx, get_script_run_ctx

from explainer.agents import (
    DEFAULT_REPORT_AUDIENCE,
    ExplainerGraphEvent,
    ReportAudience,
    run_explainer_graph,
)


REPORT_AUDIENCE_OPTIONS = {
    "stakeholder": "Stakeholder (balanced policy-facing)",
    "executive": "Executive (concise high-level)",
    "technical": "Technical (method/detail oriented)",
    "donor": "Donor (transparency/accountability)",
}

AGENT_DISPLAY = {
    "trend_analyst": {"label": "Trend Analyst", "icon": "📈"},
    "final_state_analyst": {"label": "Final State Analyst", "icon": "🎯"},
    "report_writer": {"label": "Report Writer", "icon": "📝"},
}


def _render_agent_status_panel(
    placeholder,
    agent_states: dict[str, str],
    latest_message: str | None = None,
) -> None:
    """Render live graph-agent status cards."""
    status_styles = {
        "idle": {
            "badge": "Idle",
            "bg": "#f3f4f6",
            "border": "#d1d5db",
            "text": "#4b5563",
            "shadow": "none",
        },
        "active": {
            "badge": "Thinking",
            "bg": "#ecfeff",
            "border": "#06b6d4",
            "text": "#0f172a",
            "shadow": "0 0 0.9rem rgba(6, 182, 212, 0.35)",
        },
        "done": {
            "badge": "Done",
            "bg": "#ecfdf5",
            "border": "#10b981",
            "text": "#065f46",
            "shadow": "none",
        },
        "skipped": {
            "badge": "Skipped",
            "bg": "#fff7ed",
            "border": "#f59e0b",
            "text": "#92400e",
            "shadow": "none",
        },
    }

    cards = []
    for agent_name, meta in AGENT_DISPLAY.items():
        state = agent_states.get(agent_name, "idle")
        style = status_styles[state]
        icon = escape(meta["icon"])
        label = escape(meta["label"])
        badge = escape(style["badge"])
        cards.append(
            f"<div style=\"flex:1;min-width:180px;padding:0.9rem 1rem;border-radius:14px;"
            f"border:1px solid {style['border']};background:{style['bg']};box-shadow:{style['shadow']};"
            f"transition:all 160ms ease;\">"
            f"<div style=\"display:flex;align-items:center;justify-content:space-between;gap:0.75rem;\">"
            f"<div style=\"font-size:1.5rem;line-height:1;\">{icon}</div>"
            f"<div style=\"font-size:0.78rem;font-weight:700;color:{style['text']};text-transform:uppercase;letter-spacing:0.04em;\">{badge}</div>"
            f"</div>"
            f"<div style=\"margin-top:0.6rem;font-weight:700;color:#111827;\">{label}</div>"
            f"</div>"
        )

    message_html = ""
    if latest_message:
        escaped_message = escape(latest_message)
        message_html = (
            "<div style=\"margin-top:0.85rem;padding:0.75rem 0.9rem;border-radius:12px;"
            "background:#f8fafc;border:1px solid #e5e7eb;color:#334155;\">"
            f"<strong>Current update:</strong> {escaped_message}</div>"
        )

    placeholder.markdown(
        (
            "<div style=\"display:flex;gap:0.8rem;flex-wrap:wrap;margin:0.4rem 0 0.2rem 0;\">"
            + "".join(cards)
            + "</div>"
            + message_html
        ),
        unsafe_allow_html=True,
    )


def _get_reports_dir() -> Path:
    """Resolve reports directory at project root/results/reports."""
    project_root = Path(__file__).resolve().parents[2]
    return project_root / "results" / "reports"


def _get_agent_logs_dir() -> Path:
    """Resolve agent logs directory at project root/results/reports/agent_logs."""
    return _get_reports_dir() / "agent_logs"


def _list_report_files(reports_dir: Path) -> List[Path]:
    """List markdown report files ordered by most recent first."""
    if not reports_dir.exists():
        return []
    return sorted(reports_dir.glob("*.md"), key=lambda path: path.stat().st_mtime, reverse=True)


def _list_agent_trace_files(logs_dir: Path) -> List[Path]:
    """List agent trace markdown files ordered by most recent first."""
    if not logs_dir.exists():
        return []
    return sorted(logs_dir.glob("agent_trace_*.md"), key=lambda path: path.stat().st_mtime, reverse=True)


def render_report_viewer_page() -> None:
    """Render generated report viewer page."""
    st.header("Generated Reports")
    st.caption("Browse and read stakeholder reports generated by the report writer agent.")

    reports_dir = _get_reports_dir()
    reports_dir.mkdir(parents=True, exist_ok=True)
    logs_dir = _get_agent_logs_dir()
    logs_dir.mkdir(parents=True, exist_ok=True)

    st.text_input(
        "Reports folder",
        value=str(reports_dir),
        disabled=True,
        key="reports_dir_display",
    )

    if st.button("Refresh report list", key="refresh_reports"):
        st.rerun()

    report_audience = st.selectbox(
        "Report audience mode",
        options=list(REPORT_AUDIENCE_OPTIONS.keys()),
        index=list(REPORT_AUDIENCE_OPTIONS.keys()).index(DEFAULT_REPORT_AUDIENCE),
        format_func=lambda key: REPORT_AUDIENCE_OPTIONS[key],
        key="report_audience_mode",
    )
    report_audience_mode = cast(ReportAudience, report_audience)

    st.divider()

    status_placeholder = st.empty()
    _render_agent_status_panel(
        status_placeholder,
        {agent_name: "idle" for agent_name in AGENT_DISPLAY},
        latest_message="Waiting to start report generation.",
    )

    if st.button("Generate Report", key="generate_report_btn"):
        if "summary_traj" not in st.session_state or st.session_state.summary_traj is None:
            st.error("No trained model available. Please run the trajectory analysis in the **Setup** page first.")
        else:
            with st.spinner("Generating comprehensive report..."):
                summary_traj = st.session_state.summary_traj
                agent_states = {agent_name: "idle" for agent_name in AGENT_DISPLAY}
                script_run_ctx = get_script_run_ctx()

                def on_graph_event(event: ExplainerGraphEvent) -> None:
                    if script_run_ctx is not None:
                        add_script_run_ctx(threading.current_thread(), script_run_ctx)
                    node = event.get("node", "")
                    phase = event.get("phase", "info")
                    message = event.get("message", "")
                    if node in agent_states:
                        if phase == "start":
                            agent_states[node] = "active"
                        elif phase == "end":
                            agent_states[node] = "done"
                        elif phase == "info" and "skipping" in message.lower():
                            agent_states[node] = "skipped"
                    _render_agent_status_panel(status_placeholder, agent_states, latest_message=message)

                _render_agent_status_panel(
                    status_placeholder,
                    agent_states,
                    latest_message="Preparing model artifacts for the agents.",
                )

                # Generate JSONs from summary_traj
                shap_json = summary_traj.generate_shap_json(save=False, readable_feature_names=True)
                tree_json = summary_traj.generate_tree_json(save=False)
                final_explainability_json = getattr(summary_traj, "final_explainability_json", None)
                feature_profiles_json = summary_traj.generate_llm_optimized_feature_profiles(
                    save=False,
                    top_k_features=15,
                    readable_feature_names=True,
                )
                context_json = summary_traj.generate_context_json(save=False)

                # Run agent graph with generic question
                generic_question = (
                    "Provide a comprehensive analysis of the model's feature importance evolution, "
                    "key trends across training phases, feature profiles, and actionable insights for stakeholders."
                )

                result = run_explainer_graph(
                    question=generic_question,
                    shap_json=shap_json,
                    tree_json=tree_json,
                    final_explainability_json=final_explainability_json,
                    feature_profiles_json=feature_profiles_json,
                    context_json=context_json,
                    report_audience=report_audience_mode,
                    on_event=on_graph_event,
                    save_report=True,
                    report_output_dir="results/reports",
                )

                _render_agent_status_panel(
                    status_placeholder,
                    agent_states,
                    latest_message="Report generation finished.",
                )

                if result.get("report_path"):
                    st.success(f"Report generated: {Path(result['report_path']).name}")
                    if result.get("trace_path"):
                        st.caption(f"Agent trace saved: {Path(result['trace_path']).name}")
                    st.rerun()
                else:
                    st.error("Failed to generate report.")

    st.divider()

    report_files = _list_report_files(reports_dir)
    if not report_files:
        st.info("No generated reports found yet.")
        return

    latest_report = report_files[0]
    st.success(f"Latest report: {latest_report.name}")

    options = [path.name for path in report_files]
    selected_name = st.selectbox(
        "Select report",
        options=options,
        index=0,
        key="selected_report_name",
    )
    selected_report = reports_dir / selected_name

    modified = datetime.fromtimestamp(selected_report.stat().st_mtime)
    st.caption(f"Last modified: {modified.strftime('%Y-%m-%d %H:%M:%S')}")

    content = selected_report.read_text(encoding="utf-8")

    col_a, col_b = st.columns([1, 1])
    with col_a:
        st.download_button(
            label="Download selected report",
            data=content,
            file_name=selected_report.name,
            mime="text/markdown",
            key="download_selected_report",
        )
    with col_b:
        st.write(f"File: {selected_report}")

    st.divider()
    st.markdown(content)

    st.divider()
    st.subheader("Agent Traces")
    trace_files = _list_agent_trace_files(logs_dir)
    if not trace_files:
        st.info("No agent trace logs found yet.")
        return

    latest_trace = trace_files[0]
    st.caption(f"Latest trace: {latest_trace.name}")

    trace_name = st.selectbox(
        "Select agent trace",
        options=[path.name for path in trace_files],
        index=0,
        key="selected_trace_name",
    )
    selected_trace = logs_dir / trace_name
    trace_content = selected_trace.read_text(encoding="utf-8")

    trace_col_a, trace_col_b = st.columns([1, 1])
    with trace_col_a:
        st.download_button(
            label="Download selected trace",
            data=trace_content,
            file_name=selected_trace.name,
            mime="text/markdown",
            key="download_selected_trace",
        )
    with trace_col_b:
        st.write(f"File: {selected_trace}")

    with st.expander("View selected trace", expanded=False):
        st.markdown(trace_content)
